#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'test_types'

module Test
  class Client
    include ::Thrift::Client

    def sendMessage(message)
      send_sendMessage(message)
    end

    def send_sendMessage(message)
      send_message('sendMessage', SendMessage_args, :message => message)
    end
    def capitalize(str)
      send_capitalize(str)
      return recv_capitalize()
    end

    def send_capitalize(str)
      send_message('capitalize', Capitalize_args, :str => str)
    end

    def recv_capitalize()
      result = receive_message(Capitalize_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'capitalize failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_sendMessage(seqid, iprot, oprot)
      args = read_args(iprot, SendMessage_args)
      @handler.sendMessage(args.message)
      return
    end

    def process_capitalize(seqid, iprot, oprot)
      args = read_args(iprot, Capitalize_args)
      result = Capitalize_result.new()
      result.success = @handler.capitalize(args.str)
      write_result(result, oprot, 'capitalize', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class SendMessage_args
    include ::Thrift::Struct
    MESSAGE = 1

    ::Thrift::Struct.field_accessor self, :message
    FIELDS = {
      MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class SendMessage_result
    include ::Thrift::Struct

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Capitalize_args
    include ::Thrift::Struct
    STR = 1

    ::Thrift::Struct.field_accessor self, :str
    FIELDS = {
      STR => {:type => ::Thrift::Types::STRING, :name => 'str'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Capitalize_result
    include ::Thrift::Struct
    SUCCESS = 0

    ::Thrift::Struct.field_accessor self, :success
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

end

